services:
  sortir_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - sortir_db

  sortir_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sortir
      MYSQL_USER: sortir_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
