services:
  sortir_app:
    container_name: sortir_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - sortir_db

  sortir_db:
    container_name: sortir_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sortir
      MYSQL_USER: sortir_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"   # SMTP server
      - "8025:8025"   # Web interface
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: sortir_db
      PMA_USER: sortir_user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - sortir_db

